# Generated by Django 3.0.5 on 2020-04-14 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dishclass',
            fields=[
                ('classname', models.CharField(db_column='dcname', max_length=30, verbose_name='种类名')),
                ('dishclassno', models.PositiveIntegerField(db_column='dcno', primary_key=True, serialize=False, verbose_name='种类编号')),
            ],
            options={
                'verbose_name': '菜品种类',
            },
        ),
        migrations.CreateModel(
            name='past_customer',
            fields=[
                ('id', models.CharField(db_column='pcid', max_length=30, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('name', models.CharField(db_column='pcname', max_length=30, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('1', '男'), ('0', '女')], db_column='pcsex', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(db_column='pcbir', verbose_name='生日')),
            ],
            options={
                'verbose_name': '存储客户信息',
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_id', models.CharField(db_column='rid', max_length=30, primary_key=True, serialize=False, verbose_name='房间号')),
                ('room_type', models.CharField(choices=[('1', '高级大床房'), ('2', '豪华双人大床房'), ('3', '尊贵大床房')], db_column='rtype', max_length=30, verbose_name='房间类型')),
                ('room_floor', models.PositiveIntegerField(db_column='rfloor', verbose_name='楼层')),
                ('room_deposit', models.PositiveIntegerField(db_column='rdeposit', verbose_name='订金')),
                ('room_is_booked', models.BooleanField(db_column='rbooked', default=False, verbose_name='预定状态')),
            ],
            options={
                'verbose_name': '房间',
            },
        ),
        migrations.CreateModel(
            name='preferred_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckIn.past_customer')),
            ],
            options={
                'verbose_name': '菜品偏好',
            },
        ),
        migrations.CreateModel(
            name='dish',
            fields=[
                ('dishno', models.PositiveIntegerField(db_column='dno', primary_key=True, serialize=False, verbose_name='菜品编号')),
                ('name', models.CharField(db_column='dname', max_length=30, verbose_name='菜名')),
                ('dishclassno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckIn.dishclass')),
            ],
            options={
                'verbose_name': '菜品',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.CharField(db_column='cid', max_length=30, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('name', models.CharField(db_column='cname', max_length=30, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('1', '男'), ('0', '女')], db_column='csex', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(db_column='cbir', verbose_name='生日')),
                ('is_checked', models.BooleanField(db_column='ccheck', default=False, verbose_name='入住状态')),
                ('agree_record', models.BooleanField(db_column='crecord')),
                ('face', models.ImageField(blank=True, db_column='cface', upload_to='')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckIn.room')),
            ],
            options={
                'verbose_name': '当前客户信息',
            },
        ),
    ]
