# Generated by Django 3.0.4 on 2020-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_customer',
            name='id',
            field=models.CharField(default='0', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='preferred_food',
        ),
    ]
