# Generated by Django 3.0.4 on 2020-04-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0002_auto_20200413_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='preferred_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckIn.past_customer')),
            ],
        ),
    ]
