# Generated by Django 3.0.4 on 2020-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0005_auto_20200414_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='face',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='000', max_length=30, primary_key=True, serialize=False),
        ),
    ]
