# Generated by Django 3.0.4 on 2020-04-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0006_auto_20200414_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1', '高级大床房'), ('2', '豪华双人大床房'), ('3', '尊贵大床房')], max_length=30),
        ),
    ]
