# Generated by Django 3.0.4 on 2020-04-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0007_auto_20200414_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '当前客户信息'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': '菜品'},
        ),
        migrations.AlterModelOptions(
            name='dishclass',
            options={'verbose_name': '菜品种类'},
        ),
        migrations.AlterModelOptions(
            name='past_customer',
            options={'verbose_name': '存储客户信息'},
        ),
        migrations.AlterModelOptions(
            name='preferred_food',
            options={'verbose_name': '菜品偏好'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '房间'},
        ),
    ]
